# create environment : conda env create -f conda_env.yml
# update dependencies: conda env update -f conda_env.yml
# remove environment : conda env remove -n miaplpy
# enter  environment : conda activate miaplpy
# exit   environment : conda deactivate
name: miaplpy-env
channels:
  - conda-forge
  - defaults
dependencies:
  - c-compiler
  - python>=3.9
  - cartopy
  - cvxopt
  - rasterio
  - dask>=1.0
  - dask-jobqueue>=0.3
  - defusedxml
  - h5py
  - lxml
  - matplotlib
  - numpy
  - pip
  - pyproj
  - scikit-image
  - scipy
  - gdal
  - mintpy
  - isce2
  - cython
  - setuptools
  - pulp
  - pyaps3>=0.3
  - pykml>=0.2
  - pyresample
  - pysolid
